CONFIG_ZMK_POINTING=y
CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_MOUSE=y


CONFIG_SPI=y
CONFIG_INPUT=y


CONFIG_PMW3610=y
CONFIG_PMW3610_INVERT_X=n
CONFIG_PMW3610_SMART_ALGORITHM=y

# レポート間隔を詰める
CONFIG_PMW3610_REPORT_INTERVAL_MIN=4

# PMW3610のポーリングレートを上げる
CONFIG_PMW3610_POLLING_RATE_250=y

# 動き始めのカクつき対策
CONFIG_PMW3610_FORCE_AWAKE=y

CONFIG_ZMK_BATTERY_REPORTING=y